In [1]:
import numpy as np

In [8]:
A = np.array([
    [1, 2, 0, 4],
    [3, 6, 0, 8],
    [5, 10, 0, 12],
    [7, 14, 0, 16]
])

rank = np.linalg.matrix_rank(A)
print(f"The rank of the matrix is: {rank}")


The rank of the matrix is: 2


In [10]:
A2 = np.array([
    [1, 1, 1],
    [2, 4, 3],
    [0, 0, 1]
])

# Check if the matrix is invertible
if np.linalg.matrix_rank(A2) == A2.shape[0]:
    A2_inv = np.linalg.inv(A2)
    print("Inverse of A2:\n", A2_inv)
else:
    print("Matrix does not have an inverse.")

Inverse of A2:
 [[ 2.  -0.5 -0.5]
 [-1.   0.5 -0.5]
 [ 0.   0.   1. ]]


In [12]:
A4 = np.array([
    [1, 1, 1, 1],
    [2, 1, 0, 3],
    [4, 3, 2, 1],
    [3, 0, 5, 2]
])

# Check if the matrix is invertible
if np.linalg.matrix_rank(A4) == A4.shape[0]:
    A4_inv = np.linalg.inv(A4)
    print("Inverse of A4:\n", A4_inv)
else:
    print("Matrix does not have an inverse.")

Inverse of A4:
 [[-1.375  0.25   0.375  0.125]
 [ 1.25  -0.25  -0.    -0.25 ]
 [ 0.625 -0.25  -0.125  0.125]
 [ 0.5    0.25  -0.25   0.   ]]
